# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ata_piix" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/c4b980c8-2156-4bdf-8acd-f3b1cb958186";
      fsType = "btrfs";
      options = [
        "compress=zstd"
      ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/8C5C-2F83";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/92ce20d2-8be1-4998-b6ce-59fb7ebdffda";
    fsType = "btrfs";
    options = [
      "compress=zstd"
    ];
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/disk/by-uuid/10eed79d-a0f9-4517-8fa3-256ed93d58f2";
    fsType = "btrfs";
    options = [
      "compress=zstd:9"
    ];
  };

  zramSwap = {
    enable = true;
    algorithm = "lz4";
    memoryPercent = 150;
    priority = 100;
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
